#!/bin/sh
source resources

case $BLOCK_BUTTON in
	1) notify-send -i $calendar "$(timedatectl | grep 'Time zone' | xargs | awk '{print $1,$2,$3}')";;
	2) st -e vim $0;;
	3) notify-send "$(cal)";;
esac

printf " %s%s%s |  %s%s%s" "$YL" "$(date "+%a %m.%d.%Y")" "$WT" "$GN" "$(date "+%I:%M %p")" "$WT"
