#!/bin/sh
source resources

case $BLOCK_BUTTON in
	1) notify-send "$(timedatectl | grep 'Time zone' | xargs)";;
	2) st -e vim $0;;
	3) notify-send "$(cal)";;
esac

printf " %s%s%s |  %s%s%s" "$f_YL" "$(date "+%a %m.%d.%Y")" "$f_WT" "$f_GN" "$(date "+%I:%M %p")" "$f_WT"
