#!/bin/sh
if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	wifiicon="$(awk '/^\s*w/ { print "", int($3 * 100 / 70) "% " }' /proc/net/wireless)"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon=" " || wifiicon=" "
fi

vpn="$(sed "s/.*//" /sys/class/net/tun*/operstate 2>/dev/null)"
ethernet="$(sed "s/down//;s/up//" /sys/class/net/e*/operstate 2>/dev/null)"

if [[ $vpn = "" ]]; then
	ethernet="$(sed "s/down//;s/up//" /sys/class/net/e*/operstate 2>/dev/null)"
	vpn=""
fi

printf "%s%s%s \n" "$wifiicon" $ethernet $vpn
