#!/bin/sh
. resources

case $BLOCK_BUTTON in
	1) st -e top;;
	2) st -e $EDITOR $0;;
	3) dunstify -i blivet-gui -t 5000 -r 3307 -a memory "Free disk" "$(df -h /home | tail -n 1 | awk '{print "Total: "$2, "Used: " $3}')";;
esac

printf " %s%s%s" "$BL" "$(free -h | grep Mem | awk '{print $3"/"$2}')" "$WT"
