#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "Data downloaded:" $(cat /sys/class/net/[ew]*/statistics/rx_bytes | numfmt --to=iec);;
	2) st -e vim $0;;
	3) notify-send "network devices:" "$(lspci | egrep -i --color 'network|ethernet|wireless|wi-fi')";;
esac

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes); tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)
printf "%4sB %4sB\\n" "$(numfmt --to=iec $rx)" "$(numfmt --to=iec $tx)"
