#!/bin/sh
. resources

case $BLOCK_BUTTON in
	1) dunstify -i akregator -t 3500 -r 3197 -a news "updating news..."; kill -36 $(pidof dwmblocks);;
	2) st -e $EDITOR $0;;
	3) if [ $(pgrep -c newsboat) -gt 0 ]; then dunstify -u critical -i dialog-warning "newsboat is already runing"; exit; else st -e newsboat ;fi;;
esac

printf "$(newsboat -x reload print-unread | awk '{ if ($1 != "Error:" && -z $1 && $1 != 0) print " "$1}')\n"
