#!/bin/sh
# mute
[ $(pamixer --get-mute) = true ] && printf " ^c#e83333^[mute]^c#bbbbbb^\n" && exit

# volume
vol="$(pamixer --get-volume)"
if   [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
elif [ "$vol" -gt "0"  ]; then
	icon=""
else
	printf " ^c#e83333^$vol"%%"^c#bbbbbb^\n" && exit
fi
	printf "$icon ^c#e83333^$vol"%%"^c#bbbbbb^%\n"
