#!/bin/sh
source colors

case $BLOCK_BUTTON in
	1) pamixer -t; kill -39 $(pidof dwmblocks);;
	2) st -e vim $0;;
	3) notify-send -t 5000 "$(pamixer --list-sinks | awk '{print $3,$4,$5,$6,$2}')";;
esac

# mute
[ $(pamixer --get-mute) = true ] && printf "$red mute $white" && exit

# volume
vol="$(pamixer --get-volume)"
if   [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
elif [ "$vol" -gt "0"  ]; then
	icon=""
elif [ "$vol" -le "0"  ]; then
	icon=""
fi
	printf "%s$red %s%% $white" "$icon" "$vol"
