#!/bin/sh
source resources

case $BLOCK_BUTTON in
	1) pamixer -t; kill -39 $(pidof dwmblocks);;
	2) st -e vim $0;;
	3) notify-send -t 5000 -i $sound "$(pamixer --list-sinks | xargs | awk '{print $(NF-3),$(NF-2),$(NF-1),$NF}')";;
esac

# get-mute
if [ $(pamixer --get-mute) = true ]; then printf " %s%s%s" "$f_RD" "mute " "$f_WT"; exit; fi

# get-volume
vol="$(pamixer --get-volume)"; if [$vol = ""]; then kill -39 $(pidof dwmblocks); exit; fi

if   [ "$vol" -gt "70" ]; then icon=""
elif [ "$vol" -gt "30" ]; then icon=""
elif [ "$vol" -gt "0"  ]; then icon=""
elif [ "$vol" -le "0"  ]; then icon=""
fi

printf "%s %s%s %s" "$icon" "$f_RD" "$vol%" "$f_WT"
