#!/bin/sh
# wallpaper
~/.fehbg &

# dwmblocks
export PATH="$PATH:$HOME/.dwm/modules"; dwmblocks &

# notify daemon
dunst &

# fm
/usr/local/bin/st -e lf &

# st
/usr/local/bin/st -e /bin/sh --login &

# numlock
numlockx &

# loop
#while true; do
#	dwm 2>/dev/null
#done

# MOTD
notify-send -t 10000 "$(printf 'Startup time: ' & systemd-analyze | awk '{print $16}')" &

# dwm
exec dwm
