#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

# $CPATH replaces $PATH env
CPATH="$HOME/.dwm/dmenu-items"

IFS=:
if stest -dqr -n "$cache" $CPATH; then
	stest -flx $CPATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
